# CODE REQUIREMENT 1 of 8 - welcome message with name, surname, and menu (pt-br: EXIGÊNCIA DO CÓDIGO 1 de 8 - mensagem de boas-vindas com nome, sobrenome e menu)

print("=" * 64)
print('=' * 9 + "Bem-vindo à Pizzaria do Samuel Alves Miranda!" + '=' * 10)
print("=" * 64)
print('-' * 28 + "Cardápio" + '-' * 28)
print("-" * 64)
print('=' * 8 + "| Tamanho | Pizza Salgada(PS) | Pizza Doce(PD) |" + '=' * 8)
print('-' * 8 +  "|    P    |      R$ 30.00     |    R$ 34.00    |" + '-' * 8)
print('-' * 8 +  "|    M    |      R$ 45.00     |    R$ 48.00    |" + '-' * 8)
print('-' * 8 +  "|    G    |      R$ 60.00     |    R$ 66.00    |" + '-' * 8)
print("=" * 64)