# CODE REQUIREMENT 1 of 8 - welcome message with name, surname, and menu (pt-br: EXIGÊNCIA DO CÓDIGO 1 de 8 - mensagem de boas-vindas com nome, sobrenome e menu)

print("=============================================")
print("Bem-vindo à Pizzaria do Samuel Alves Miranda!")
print("=============================================")
print("\nMENU:")
print("\nSabores:")
print("Pizza Salgada")
print("Pizza Doce")
print("\nTamanhos:")
print("  P - Pequena")
print("  M - Média")
print("  G - Grande")